use base64::Engine;
use jsonwebtoken::decode_header;
use jwt_simple::reexports::coarsetime::Duration;
use rusty_jwt_tools::prelude::*;

use rusty_jwt_tools::jwk_thumbprint::JwkThumbprint;
use rusty_jwt_tools::jwt_key::JwtKey;

#[test]
fn e2e_jwt() {
    let mut results = vec![];

    for (key, backend_keys, hash_alg) in keys() {
        let alg = key.alg;
        println!("# {alg:?} - {hash_alg:?}");

        let nonce: BackendNonce = rand_base64_str(32).into(); // generated by wire-server
        let challenge: AcmeNonce = rand_base64_str(32).to_string().into(); // generated by ACME server
        let user = uuid::Uuid::new_v4().to_string();
        let cid = rand::random::<u64>();
        let (domain, team, handle, display_name) = ("wire.com", "wire", "beltram_wire", "Beltram Maldant");
        let alice = ClientId::try_new(&user, cid, domain).unwrap();
        let audience = "https://stepca:32902/acme/wire/challenge/I16phsvAPGbruDHr5Bh6akQVPKP6OO5v/dF2LHNmGI20R8rzzcgnrCSv789XcFEyL".parse().unwrap();
        let htu: Htu = format!("https://wire.example.com/clients/{cid}/access-token")
            .as_str()
            .try_into()
            .unwrap();
        let htm = Htm::Post;
        let leeway: u16 = 5;
        let expiry = Duration::from_days(1).into();
        let max_expiration: u64 = 2136351646; // somewhere in 2037
        let handle = Handle::from(handle).try_to_qualified(domain).unwrap();
        let dpop = Dpop {
            htu: htu.clone(),
            htm,
            challenge: challenge.clone(),
            handle: handle.clone(),
            team: team.into(),
            display_name: display_name.to_string(),
            extra_claims: None,
        };

        let client_sk = key.sk;
        // Wire app generates a DPoP JWT token
        let client_dpop =
            RustyJwtTools::generate_dpop_token(dpop, &alice, nonce.clone(), audience, expiry, alg, &client_sk).unwrap();

        println!(
            "1. generate dpop:\nclient signature key:\n{client_sk}\nDpop token:\nhttps://jwt.io/#id_token={client_dpop}\n"
        );

        let backend_sk = backend_keys.sk;

        // wire-server now validates the 'client_dpop' and generates an access token
        let access_token = RustyJwtTools::generate_access_token(
            &client_dpop,
            &alice,
            handle.clone(),
            display_name,
            team.into(),
            nonce.clone(),
            htu.clone(),
            htm,
            leeway,
            max_expiration,
            backend_sk.clone(),
            hash_alg,
            5,
            core::time::Duration::from_secs(360),
        )
        .unwrap();

        println!(
            "2. generate access token:\nwire-server signature key:\n{backend_sk}\naccess token:\nhttps://jwt.io/#id_token={access_token}\n"
        );

        // now acme server will verify the access token
        let backend_pk = backend_keys.pk;
        let dpop_header = decode_header(&client_dpop).unwrap();
        let dpop_jwk = dpop_header.jwk.unwrap();
        let kid = JwkThumbprint::generate(&dpop_jwk, hash_alg).unwrap().kid;
        let verify = RustyJwtTools::verify_access_token(
            &access_token,
            &alice,
            &handle,
            display_name,
            &team.into(),
            challenge,
            leeway,
            max_expiration,
            htu.clone(),
            backend_pk.clone(),
            kid,
            hash_alg,
            5,
        );
        println!("3. verify access token\nwire-server public signature key:\n{backend_pk}");
        if verify.is_ok() {
            println!("✅ access token verified");
            results.push(verify);
        } else {
            panic!("❌ access token invalid because {:?}", verify);
        }
        println!("---------------------------------------------------------------------\n");
    }
    assert!(results.into_iter().all(|v| v.is_ok()));
}

fn keys() -> Vec<(JwtKey, JwtKey, HashAlgorithm)> {
    vec![
        (
            JwtKey::new_key(JwsAlgorithm::EdDSA),
            JwtKey::new_key(JwsAlgorithm::EdDSA),
            HashAlgorithm::SHA256,
        ),
        (
            JwtKey::new_key(JwsAlgorithm::ES256),
            JwtKey::new_key(JwsAlgorithm::ES256),
            HashAlgorithm::SHA256,
        ),
        (
            JwtKey::new_key(JwsAlgorithm::ES384),
            JwtKey::new_key(JwsAlgorithm::ES384),
            HashAlgorithm::SHA384,
        ),
        (
            JwtKey::new_key(JwsAlgorithm::ES512),
            JwtKey::new_key(JwsAlgorithm::ES512),
            HashAlgorithm::SHA512,
        ),
    ]
}

pub fn rand_base64_str(size: usize) -> String {
    use rand::distributions::{Alphanumeric, DistString};
    let challenge: String = Alphanumeric.sample_string(&mut rand::thread_rng(), size);
    base64::prelude::BASE64_URL_SAFE_NO_PAD.encode(challenge)
}
