##################################### Haskell ####################################

[tasks.hs-test]
script = '''
    cargo build --features haskell

    cd bindings/haskell
    # link Rust libs we just built
    # required because cabal does not support relative paths outside its root dir :/
    ln -fs ../../../target .

    # test the Haskell bindings
    cabal test --test-show-details=always --test-option=--color
'''
