use jwt_simple::prelude::*;

use crate::jwk_thumbprint::JwkThumbprint;
use crate::jwt::new_jti;
use crate::prelude::*;

pub mod generate;
mod verify;

/// Claims in an access token
///
/// Specified in [OAuth 2.0 Demonstrating Proof-of-Possession at the Application Layer (DPoP)][1]
///
/// [1]: https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-11.html
#[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
#[cfg_attr(test, derive(Default))]
pub struct Access {
    /// ACME server nonce
    #[serde(rename = "chal")]
    pub challenge: AcmeNonce,
    /// Hash of the JWK, see [JwkThumbprint]
    #[serde(rename = "cnf")]
    pub cnf: JwkThumbprint,
    /// Proof of possession in form of a Dpop JWT token generated by [RustyJwtTools::generate_dpop_token]
    #[serde(rename = "proof")]
    pub proof: String,
    /// Client identifier as defined in [RFC8693](https://datatracker.ietf.org/doc/html/rfc8693#section-4.3)
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// wire-server API version
    #[serde(rename = "api_version")]
    pub api_version: u32,
    /// Scope as defined in [RFC8693](https://datatracker.ietf.org/doc/html/rfc8693#section-4.2)
    #[serde(rename = "scope")]
    pub scope: String,
    /// Allows passing extra arbitrary data which will end up in access token claims
    #[serde(flatten, skip_serializing_if = "Option::is_none")]
    pub extra_claims: Option<serde_json::Value>,
}

impl Access {
    /// JWT claim 'exp' (expiration) in seconds (90 days by default)
    ///
    /// Specified in [RFC 7519 Section 4.1.4: JSON Web Token (JWT)][1]
    ///
    /// [1]: https://tools.ietf.org/html/rfc7519#section-4.1.4
    pub const EXP: u64 = 3600 * 24 * 90; // 90 days

    /// Access token header 'typ'
    pub const TYP: &'static str = "at+jwt";

    /// Current wire-server API version
    pub const WIRE_SERVER_API_VERSION: u32 = 3;

    /// Current wire-server API version
    pub const DEFAULT_SCOPE: &'static str = "wire_client_id";

    /// we want "nbf" slightly in the past to prevent clock drifts or problems non-monotonic hosts
    pub(crate) const NBF_LEEWAY_SECONDS: u64 = 5;

    pub fn into_jwt_claims(
        self,
        client_id: &ClientId,
        nonce: BackendNonce,
        issuer: Htu,
        audience: Htu,
    ) -> JWTClaims<Self> {
        let exp = Duration::from_secs(Self::EXP);
        let nbf = coarsetime::Clock::now_since_epoch() - Duration::from_secs(Self::NBF_LEEWAY_SECONDS);
        Claims::with_custom_claims(self, exp)
            .invalid_before(nbf)
            .with_jwt_id(new_jti())
            .with_subject(client_id.to_uri())
            .with_nonce(nonce.to_string())
            .with_issuer(issuer)
            .with_audience(audience)
    }
}
