//! Generic Jwt utilities

use jsonwebtoken::{
    DecodingKey, Validation, decode,
    errors::{Error, ErrorKind},
};
use jwt_simple::{claims::JWTClaims, reexports::coarsetime::Duration};
use serde::{Serialize, de::DeserializeOwned};

use crate::prelude::*;

/// Global trait to verify a Jwt token
#[derive(Debug, Clone)]
pub struct Verify<'a> {
    /// client_id
    pub client_id: &'a ClientId,
    /// nonce
    pub backend_nonce: Option<&'a BackendNonce>,
    /// leeway
    pub leeway: u16,
    /// issuer
    pub issuer: Option<Htu>,
}

impl From<&Verify<'_>> for VerificationOptions {
    fn from(v: &Verify<'_>) -> Self {
        Self {
            accept_future: false,
            required_key_id: None, // we don't verify 'jti', just enforce its presence
            required_subject: Some(v.client_id.to_uri()),
            required_nonce: v.backend_nonce.map(|n| n.to_string()),
            time_tolerance: Some(UnixTimeStamp::from_secs(v.leeway as u64)),
            allowed_issuers: v.issuer.as_ref().map(|i| HashSet::from([i.to_string()])),
            ..Default::default()
        }
    }
}

/// Verifies JWT token standard headers
pub trait VerifyJwtHeader {
    /// Verifies a Jwt token header
    fn verify_jwt_header(&self) -> RustyJwtResult<JwsAlgorithm>;
}

impl VerifyJwtHeader for TokenMetadata {
    fn verify_jwt_header(&self) -> RustyJwtResult<JwsAlgorithm> {
        // fails when the algorithm is not supported
        let alg = JwsAlgorithm::try_from(self.algorithm())?;
        Ok(alg)
    }
}

/// Verifies a Jwt token
pub trait VerifyJwt {
    /// Verifies the JWT token given a JWK
    ///
    /// # Arguments
    /// * `key` - Public signature key
    /// * `client_id` - client identifier
    /// * `backend_nonce` - optional nonce generated by wire-server
    /// * `max_expiration` - token's 'exp' threshold
    /// * `leeway` - The maximum number of seconds of clock skew the implementation will allow
    fn verify_jwt<T>(
        &self,
        alg: JwsAlgorithm,
        key: &DecodingKey,
        max_expiration: u64,
        // expected_cnf: Option<&JwkThumbprint>,
        // actual_cnf: Option<fn(&JWTClaims<T>) -> &JwkThumbprint>,
        // custom: Option<fn(&JWTClaims<T>) -> RustyJwtResult<JWTClaims<T>>>,
        verify: Verify,
    ) -> RustyJwtResult<JWTClaims<T>>
    where
        T: Serialize + DeserializeOwned;
}

impl VerifyJwt for &str {
    fn verify_jwt<T>(
        &self,
        alg: JwsAlgorithm,
        key: &DecodingKey,
        max_expiration: u64,
        // expected_cnf: Option<&JwkThumbprint>,
        // actual_cnf: Option<fn(&JWTClaims<T>) -> &JwkThumbprint>,
        // custom: Option<fn(&JWTClaims<T>) -> RustyJwtResult<JWTClaims<T>>>,
        verify: Verify,
    ) -> RustyJwtResult<JWTClaims<T>>
    where
        T: Serialize + DeserializeOwned,
    {
        // Setup the validation
        let mut validation = Validation::new(alg.into());
        let mut required_claims = vec!["exp", "sub", "nbf"];

        if let Some(issuer) = verify.issuer {
            required_claims.push("iss");
            validation.set_issuer(&[issuer]);
        }

        validation.set_required_spec_claims(&required_claims);
        validation.validate_aud = false;
        validation.validate_exp = true;
        validation.validate_nbf = true;
        validation.leeway = verify.leeway.into();
        validation.sub = Some(verify.client_id.to_uri());

        // Get the token claims, validating the above via jsonwebtoken
        let token = decode::<JWTClaims<T>>(self, key, &validation).map_err(jwt_error_mapping)?;
        let claims = token.claims;

        // custom validations
        claims.jwt_id.as_ref().ok_or(RustyJwtError::MissingTokenClaim("jti"))?;
        claims.issued_at.ok_or(RustyJwtError::MissingTokenClaim("iat"))?;
        claims.invalid_before.ok_or(RustyJwtError::MissingTokenClaim("nbf"))?;
        claims.jwt_id.as_ref().ok_or(RustyJwtError::MissingTokenClaim("jti"))?;
        let exp = claims.expires_at.ok_or(RustyJwtError::MissingTokenClaim("exp"))?;
        if exp > Duration::from_secs(max_expiration) {
            return Err(RustyJwtError::TokenLivesTooLong);
        }

        if let Some(backend_nonce) = verify.backend_nonce {
            let nonce = claims
                .nonce
                .as_deref()
                .ok_or(RustyJwtError::MissingTokenClaim("nonce"))?;

            if nonce != backend_nonce.as_str() {
                return Err(RustyJwtError::DpopNonceMismatch);
            }
        }

        Ok(claims)
    }
}

/// Maps jsonwebtoken::errors::Error to RustyJwtError
pub fn jwt_error_mapping(e: Error) -> RustyJwtError {
    match e.into_kind() {
        ErrorKind::MissingRequiredClaim(claim) => RustyJwtError::MissingTokenClaim(Box::leak(claim.into_boxed_str())),

        ErrorKind::InvalidSubject => RustyJwtError::TokenSubMismatch,

        ErrorKind::ExpiredSignature => RustyJwtError::TokenExpired,

        // This mapping assumes that if an nbf is in the future it is a dpop validation error
        ErrorKind::ImmatureSignature => RustyJwtError::DpopNotYetValid,

        // This mapping assumes that if an invalid issuer occurs,
        // that this happens in dpop htu verification
        ErrorKind::InvalidIssuer => RustyJwtError::DpopHtuMismatch,

        // DPoP claims failing because of serde
        ErrorKind::Json(error) => {
            let msg = error.to_string();

            match msg.as_str() {
                r if r.starts_with("missing field `chal`") => RustyJwtError::MissingTokenClaim("chal"),
                r if r.starts_with("missing field `htm`") => RustyJwtError::MissingTokenClaim("htm"),
                r if r.starts_with("missing field `htu`") => RustyJwtError::MissingTokenClaim("htu"),
                r if r.starts_with("missing field `cnf`") => RustyJwtError::MissingTokenClaim("cnf"),
                r if r.starts_with("missing field `proof`") => RustyJwtError::MissingTokenClaim("proof"),
                r if r.starts_with("missing field `api_version`") => RustyJwtError::MissingTokenClaim("api_version"),
                r if r.starts_with("missing field `client_id`") => RustyJwtError::MissingTokenClaim("client_id"),
                r if r.starts_with("missing field `scope`") => RustyJwtError::MissingTokenClaim("scope"),
                r if r.starts_with("missing field `handle`") => RustyJwtError::MissingTokenClaim("handle"),
                r if r.starts_with("missing field `name`") => RustyJwtError::MissingTokenClaim("name"),
                _ => RustyJwtError::InvalidToken(msg),
            }
        }
        other => RustyJwtError::InvalidToken(format!("{other:?}")),
    }
}
