[package]
name = "wire-e2e-identity"
description = "Public API for Wire end to end identity"
version = "0.9.0"
edition = "2021"
repository = "https://github.com/wireapp/rusty-jwt-tools"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rusty-acme = { version = "0.9.0", path = "../acme" }
rusty-jwt-tools = { version = "0.9.0", path = "../jwt" }
jwt-simple = { workspace = true }
derive_more = { workspace = true, features = ["deref", "from", "into"] }
url = { workspace = true }
zeroize = { workspace = true }
uuid = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
x509-cert = { workspace = true, optional = true }
const-oid = { workspace = true, optional = true }
time = { workspace = true, optional = true }
rcgen = { workspace = true, optional = true }

[dev-dependencies]
wire-e2e-identity = { version = "0.9.0", path = ".", features = ["identity-builder"] }
rusty-jwt-tools = { version = "0.9.0", path = "../jwt", features = ["test-utils", "rsa"] }
rand = { workspace = true }
base64 = { workspace = true }
url = { workspace = true }
itertools = { workspace = true }
uuid = { workspace = true }
wasm-bindgen-test = { workspace = true }
hex = { workspace = true }
webbrowser = { workspace = true }
rusty-jwt-cli = { version = "0.9.0", path = "../cli" }

openidconnect = { workspace = true }
html_parser = { workspace = true }
scraper = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
lazy_static = { workspace = true }
portpicker = { workspace = true }
pem = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
rusty-acme = { version = "0.9.0", path = "../acme" }
reqwest = { version = "0.11", features = ["json", "cookies"], default_features = false }
tokio = { version = "1.5", features = ["macros"], default_features = false }
hyper = { version = "0.14", features = ["server"], default_features = false }
native-tls = { version = "0.2", features = ["vendored"] }
asserhttp = { version = "0.6", features = ["reqwest"] }
testcontainers = "0.15"
oauth2 = "4.3"
http = "0.2"
keycloak = "21"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
rusty-acme = { version = "0.9.0", path = "../acme" }

[features]
default = []
identity-builder = ["dep:rcgen", "dep:rand", "dep:uuid", "dep:x509-cert", "dep:const-oid", "dep:time", "rusty-jwt-tools/test-utils"]
