use clap::{Parser, Subcommand};

pub mod access_verify;
pub mod build;
pub mod jwk;
pub mod parse;
pub mod pem;
pub mod utils;

/// Simple program to greet a person
#[derive(Debug, Parser)]
#[command(
    version,
    about,
    name = "rusty-jwt-cli",
    bin_name = "rusty-jwt-cli",
    rename_all = "kebab-case"
)]
struct RustyCli {
    #[clap(subcommand)]
    cmd: Commands,
}

#[derive(Debug, Subcommand)]
#[allow(clippy::enum_variant_names)]
enum Commands {
    /// Create a new JWT
    JwtBuild {
        #[command(flatten)]
        delegate: build::BuildJwt,
    },
    /// Parse (debug) a JWT
    JwtParse {
        #[command(flatten)]
        delegate: parse::ParseJwt,
    },
    /// Parse (debug) a PEM key into JWK (with thumbprint)
    JwkParse {
        #[command(flatten)]
        delegate: jwk::ParseJwk,
    },
    /// Verify an access token generated by wire-server for e2e identity purpose
    VerifyAccess {
        #[command(flatten)]
        delegate: access_verify::AccessVerify,
    },
}

fn main() -> anyhow::Result<()> {
    let cli: RustyCli = RustyCli::parse();
    match cli.cmd {
        Commands::JwtBuild { delegate } => delegate.execute()?,
        Commands::JwtParse { delegate } => delegate.execute()?,
        Commands::JwkParse { delegate } => delegate.execute()?,
        Commands::VerifyAccess { delegate } => delegate.execute()?,
    };
    Ok(())
}
