name: toml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uncenter/setup-taplo@v1
      - uses: wireapp/setup-fd@v0.1.0
      - run: fd --glob '*.toml' -X taplo fmt --check
